### ISSUE TITLE
Allow passing arguments with `-m`

### ISSUE THREAD

**Issue by phiresky** [bulletmark/debugpy-run#4]
Right now it seems impossible to pass cmd line args when running a module. For example for unit tests:

```
debugpy-run -m unittest discover -v -p"*tests.py" 
```

throws: error: argument program: not allowed with argument -m/--module

It seems to think that the first argument (`discover`) is the program name. It doesn't work with `--` either, e.g.

```
debugpy-run -m unittest -- discover -v -p"*tests.py" 
```

**Comment by bulletmark** [comment]
Yes, unfortunately the argument options in upstream `debugpy` have been defined in an awkward manner and I have to remain compatible. Please try the master branch and let me know if it now works for you?

**Comment by phiresky** [comment]
that seems to work for my use case, yes. thanks!

**Comment by bulletmark** [comment]
New [release 1.4](https://github.com/bulletmark/debugpy-run/releases/tag/1.4) fixes this issue.
