### ISSUE TITLE
Allow passing argument to module debug with -m

### ISSUE THREAD

**Issue by sonack** [bulletmark/debugpy-run#5]
If run the following command
```
debugpy-run -m torch.distributed.launch --nproc_per_node=4 examples/run_funsd.py \
        --model_name_or_path microsoft/layoutlm-base-uncased \
        --output_dir /tmp/test-ner \
        --do_train \
        --do_predict \
        --max_steps 1000 \
        --warmup_ratio 0.1 \
        --fp16
```
It will complain
```
debugpy-run: error: unrecognized arguments: --nproc_per_node=4
```
seems like debugpy-run take `nproc_per_node=4` as its own argument rather than the module `torch.distributed.launch`.

---

My current workaround is to quote these module arguments with the module name as a whole：
```
debugpy-run -m "torch.distributed.launch --nproc_per_node=4" examples/run_funsd.py \
        --model_name_or_path microsoft/layoutlm-base-uncased \
        --output_dir /tmp/test-ner \
        --do_train \
        --do_predict \
        --max_steps 1000 \
        --warmup_ratio 0.1 \
        --fp16
```
Or quote all the arguments like this：
```
debugpy-run -m "torch.distributed.launch --nproc_per_node=4 examples/run_funsd.py \
        --model_name_or_path microsoft/layoutlm-base-uncased \
        --output_dir /tmp/test-ner \
        --do_train \
        --do_predict \
        --max_steps 1000 \
        --warmup_ratio 0.1 \
        --fp16"
```
which is ugly and break down the log format.

I am wondering if there is a better way to deal with such a use case, especially when I debug distributed pytorch programs?
Waiting for your reply & many thanks to your efforts on such an excellent auxiliary utility！

**Comment by bulletmark** [comment]
Does this work?
```
debugpy-run -m torch.distributed.launch -- --nproc_per_node=4 examples/run_funsd.py \
        --model_name_or_path microsoft/layoutlm-base-uncased \
        --output_dir /tmp/test-ner \
        --do_train \
        --do_predict \
        --max_steps 1000 \
        --warmup_ratio 0.1 \
        --fp16
```

**Comment by sonack** [comment]
> Does this work?
> 
> ```
> debugpy-run -m torch.distributed.launch -- --nproc_per_node=4 examples/run_funsd.py \
>         --model_name_or_path microsoft/layoutlm-base-uncased \
>         --output_dir /tmp/test-ner \
>         --do_train \
>         --do_predict \
>         --max_steps 1000 \
>         --warmup_ratio 0.1 \
>         --fp16
> ```

Yes, it works.

**Comment by bulletmark** [comment]
So that is the solution then. FYI, developers working on Linux need to know that ['--' trick](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean).
